export const INVOICES_LIST_REQUEST = 'INVOICES_LIST_REQUEST';
export const INVOICES_LIST_SUCCESS = 'INVOICES_LIST_SUCCESS';
export const INVOICES_LIST_FAIL = 'INVOICES _LIST_FAIL';

  
export const INVOICES_DETAILS_REQUEST = 'INVOICES_DETAILS_REQUEST';
export const INVOICES_DETAILS_SUCCESS = 'INVOICES_SUCCESS';
export const INVOICES_DETAILS_FAIL = 'INVOICES_DETAILS_FAIL';

