export const PROPERTY_ADD_REQUEST='PROPERTY_ADD_REQUEST';
export const PROPERTY_ADD_SUCCESS='PROPERTY_ADD_SUCCESS';
export const PROPERTY_ADD_FAIL='PROPERTY_ADD_FAIL';

export const PROPERTY_LIST_REQUEST = 'PROPERTY_LIST_REQUEST';
export const PROPERTY_LIST_SUCCESS = 'PROPERTY_LIST_SUCCESS';
export const PROPERTY_LIST_FAIL = 'PROPERTY_LIST_FAIL';

export const PROPERTY_UPDATE_REQUEST ='PROPERTY_UPDATE_REQUEST';
export const PROPERTY_UPDATE_SUCCESS ='PROPERTY_UPDATE_SUCCESS';
export const PROPERTY_UPDATE_FAIL    ='PROPERTY_UPDATE_FAIL';


export const PROPERTY_DETAILS_REQUEST = 'PROPERTY_DETAILS_REQUEST';
export const PROPERTY_DETAILS_SUCCESS = 'PROPERTY_DETAILS_SUCCESS';
export const PROPERTY_DETAILS_FAIL = 'PROPERTY_DETAILS_FAIL';

export const PROPERTY_SAVE_REQUEST = 'PROPERTY_SAVE_REQUEST';
export const PROPERTY_SAVE_SUCCESS = 'PROPERTY_SAVE_SUCCESS';
export const PROPERTY_SAVE_FAIL = 'PROPERTY_SAVE_FAIL';

export const PROPERTY_DELETE_REQUEST = 'PROPERTY_DELETE_REQUEST';
export const PROPERTY_DELETE_SUCCESS = 'PROPERTY_DELETE_SUCCESS';
export const PROPERTY_DELETE_FAIL = 'PROPERTY_DELETE_FAIL';

export const PROPERTY_REVIEW_SAVE_REQUEST = 'PROPERTY_REVIEW_SAVE_REQUEST';
export const PROPERTY_REVIEW_SAVE_SUCCESS = 'PROPERTY_REVIEW_SAVE_SUCCESS';
export const PROPERTY_REVIEW_SAVE_FAIL    =  'PROPERTY_REVIEW_SAVE_FAIL';
export const PROPERTY_REVIEW_SAVE_RESET   = 'PROPERTY_REVIEW_SAVE_RESET';